require './lib/sswaffles/bucketcollection.rb'
require './lib/sswaffles/bucket.rb'
require './lib/sswaffles/objectcollection.rb'
require './lib/sswaffles/object.rb'
require './lib/sswaffles/backends/memory.rb'
require './lib/sswaffles/backends/disk.rb'
require './lib/sswaffles/backends/amazonreadonly.rb'
require './lib/sswaffles/storage.rb'